// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF9tgz7vQpjCMZyddAd0zmB06gU-lCf6I',
    appId: '1:681144144752:web:17d18441a5bc849e65b5b5',
    messagingSenderId: '681144144752',
    projectId: 'doctor-appointment-bdda5',
    authDomain: 'doctor-appointment-bdda5.firebaseapp.com',
    storageBucket: 'doctor-appointment-bdda5.appspot.com',
    measurementId: 'G-FYN8VNXVXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0brPIVacN1jCDOjikaAFJFyOO6CzVMMQ',
    appId: '1:681144144752:android:fbd2d7dadca7af8e65b5b5',
    messagingSenderId: '681144144752',
    projectId: 'doctor-appointment-bdda5',
    storageBucket: 'doctor-appointment-bdda5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm74bb1rgOVZGwMIdnn9V_PAilHReIxTo',
    appId: '1:681144144752:ios:b6b64b4c3ee1aeba65b5b5',
    messagingSenderId: '681144144752',
    projectId: 'doctor-appointment-bdda5',
    storageBucket: 'doctor-appointment-bdda5.appspot.com',
    iosBundleId: 'com.example.doctorAppointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm74bb1rgOVZGwMIdnn9V_PAilHReIxTo',
    appId: '1:681144144752:ios:47bb0f188b682f8165b5b5',
    messagingSenderId: '681144144752',
    projectId: 'doctor-appointment-bdda5',
    storageBucket: 'doctor-appointment-bdda5.appspot.com',
    iosBundleId: 'com.example.doctorAppointment.RunnerTests',
  );
}
